### ISSUE TITLE
Change update patching

### ISSUE THREAD

**Issue by AetherOF** [whoblitzell/OpenFaldonBugs#24]
Map patching from 1x1 to 3x3 (fixes some update/patch issues)
Since updates are working better now and saving.
Also please force map updates.

We can set a delay of grid sections updates if you want, and have them 1 second apart if there is more than 1. That should help. First one can start instantly, so patching should take 2 seconds for any given movement in a direction.

**Comment by AetherOF** [comment]
Delay is hardly needed though since lag will only remain at first time the player patches the area... Up to you and what you want to do/test etc...

**Comment by whoblitzell** [comment]
Fixed.
