### ISSUE TITLE
sometimes character appear as naked to others

### ISSUE THREAD

**Issue by KaiyuenW** [whoblitzell/OpenFaldonBugs#29]
character sometimes appear as naked to other. re-equiping will only show it for a second then back to naked. 
![Capture](https://user-images.githubusercontent.com/54672390/110197963-d6079900-7eb3-11eb-956e-e7286e1daef6.JPG)

**Comment by whoblitzell** [comment]
Looking at this soon,

**Comment by whoblitzell** [comment]
Kaiyuen fixed this heh
