### ISSUE TITLE
Large quantity of stackable appear incorrectly

### ISSUE THREAD

**Issue by KaiyuenW** [whoblitzell/OpenFaldonBugs#32]
1) If you put a stack of more than 32,767 on market, the quantity becomes incorrect. 
eg. 32,768 appear as 65,536 and 50,000 appear as 82,768.
You wouldn't be able to buy more than the actual amount though.

2) If you have a stack of 32,768 (only this amount) in inventory, the quantity doesn't show and if you try to put it in bank, there is no prompt asking for quantity as if I'm putting in one but 32768 will go in. 

3) If you have a stack of more than 32,000 in inventory, it doesn't show in snoop.

(tested with lumbers)

**Comment by KaiyuenW** [comment]
quantity 65354 up to 98032 in trade will display incorrectly.

![4](https://user-images.githubusercontent.com/54672390/113101648-78b7fb00-9259-11eb-900c-02e4c306ae24.JPG)
![3](https://user-images.githubusercontent.com/54672390/113101643-7786ce00-9259-11eb-81ec-d7923d55f645.JPG)

**Comment by whoblitzell** [comment]
I will fix this soon.
