### ISSUE TITLE
Some freed pets can't be attacked

### ISSUE THREAD

**Issue by KaiyuenW** [whoblitzell/OpenFaldonBugs#34]
Some freed pets becomes a peaceful creature that can't be attacked but it can attack you. 
![Faldon12 FSA](https://user-images.githubusercontent.com/54672390/112714713-7e070400-8f40-11eb-93c3-b661f64a7663.jpg)

Sometimes they would immediately disappear back to its spawn coordinate but on the map I freed it. e.g. an STT from (x309,y421) on map 8 gets freed on map 7 would go (x309,y421). 
Here are 2 of the 3 STT that were freed in val and teleported to behind thief town. The other is in the 1st SS, stuck in val.
![Faldon13 FSA](https://user-images.githubusercontent.com/54672390/112714825-346ae900-8f41-11eb-91b8-9e018b2355cd.png)

When I log off and on with pets, they sometimes are not my pets anymore, they can't be attacked and they continue to recognize my jester hat and will say hunger cleared.

**Comment by whoblitzell** [comment]
Fixed,
