### ISSUE TITLE
skill point gain only goes up to next whole number

### ISSUE THREAD

**Issue by KaiyuenW** [whoblitzell/OpenFaldonBugs#36]
If I have for example 60.85 Blacksmith, I'll gain 0.14 by producing a ringmail. I now have 60.99, if I make another ringmail, I'll only gain 0.01 to reach the next whole number for blacksmith.

**Comment by whoblitzell** [comment]
This is fixed in a future release (Open Faldon Alpha edition) but thanks for letting me know (👍
