### ISSUE TITLE
double login same character will end up on map 0

### ISSUE THREAD

**Issue by KaiyuenW** [whoblitzell/OpenFaldonBugs#60]
1st login gets kicked off, 2nd login looks fine but is actually on map 0. 
![image](https://user-images.githubusercontent.com/54672390/131581848-a7dcc2e9-688b-4dab-9015-ac685a7bfc4e.png)
clear command will move to map 0
![image](https://user-images.githubusercontent.com/54672390/131581864-cb492c4a-4b6f-4143-958b-d687f6da036c.png)

**Comment by whoblitzell** [comment]
This shouldnt be possible anymore
