### ISSUE TITLE
Pets can be controlled by previous owner and will warp to them to protect them

### ISSUE THREAD

**Issue by KaiyuenW** [whoblitzell/OpenFaldonBugs#8]
Pets given to someone else still counts towards your pet slot and you can still control them with commands such as pets slay and pets free. Pets follow new owner but they will warp to you to help you fight even while on a different map and not in party. The new pet owner gets shared exp from pet.

**Comment by whoblitzell** [comment]
I cannot duplicate this but will review pets give logic
