### ISSUE TITLE
Dupe mob with zoo

### ISSUE THREAD

**Issue by KaiyuenW** [whoblitzell/OpenFaldonBugs#9]
if you try to take a pet out of zoo but have reached slot limit, the pet will be out as a free mob and you will still another one in zoo. Sometimes that spawned mob is a 'peaceful creature' that can't be attacked.

**Comment by whoblitzell** [comment]
Looking into this...

**Comment by whoblitzell** [comment]
Update is that this is still a problem I need to look into with the McGrew script. Will check soon

**Comment by whoblitzell** [comment]
fixed this @KaiyuenW
